name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Good Morning"
      - name: Print Bye
        run: echo "Good Bye!!!"
    
    
	
